apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: shopify
        image: doovid1000/shopify_arm64:1.0.80
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_PASSWORD
          value: "mongotemp"
---
apiVersion: v1
kind: Service
metadata:
  name: shop-service
spec:
  selector:
    app: webapp
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer
        